version: '3.8'
services:
  gateway:
    image: gateway-image
    container_name: gateway
    ports:
      - "8081:8081"
    depends_on:
      - company-service
      - employee-service

  company-service:
    image: company-image
    container_name: company-service
    ports:
      - "8082:8082"
    depends_on:
      - employee-service
    restart: always

  employee-service:
    image: employee-image
    container_name: employee-service
    ports:
      - "8083:8083"
    depends_on:
      - frontend
    restart: always
  
  frontend:
    image: frontend-image
    container_name: frontend
    ports:
      - "8080:8080"
    restart: always