### Get all companies
GET http://localhost:8080/companies

### Add new company
PUT http://localhost:8080/companies
Content-Type: application/json

{
  "name": "Allstar",
  "sector": "Sport"
}

### Get a company
GET http://localhost:8080/companies/PKO
Accept: application/json

### Getting company by name that does not exist
GET http://localhost:8080/companies/NotExistingCompany

### Updating company by name
PUT http://localhost:8080/companies/Apple
Content-Type: application/json

{
  "name": "Google",
  "sector": "IT"
}

### Deleting company by name
DELETE http://localhost:8080/companies/Zara
Accept: application/json

### Getting all employees
GET http://localhost:8080/companies/employees
Accept: application/json

### Listing all employees of a company
GET http://localhost:8080/companies/PKO/employees
Accept: application/json

### Adding new employee to a company
PUT http://localhost:8080/companies/PKO/employees
Content-Type: application/json

{
  "name": "Amelia Dombrowska",
  "seniority": "Junior"
}


